app/models.py
# from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

from . import db, login_manager  # Import db from the main __init__.py file


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    # id of the user in database (primary)
    id = db.Column('user_id', db.Integer(), primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    # You can add additional fields like 'team_id', 'role', etc.
    # @password.setter
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User {}>'.format(self.username)


class Category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    items = db.relationship('Item', backref='category', lazy=True)


class Item(db.Model):
    __tablename__ = 'item'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)


# def init_db():
#     db.create_all()
#
#     # Create a test user
#     new_user = User()
#     new_user.display_name = 'Nathan'
#     db.session.add(new_user)
#     db.session.commit()
#
#     new_user.datetime_subscription_valid_until = datetime.datetime(2019, 1, 1)
#     db.session.commit()

def init_db():
    # Create categories
    category1 = Category(name='Networking Devices')
    category2 = Category(name='Cabling Tools')
    category3 = Category(name='Climbers, Belts, Espression, Spellaton Machine, Optical Fiber Identifier')
    category4 = Category(name='Splitter Sizes 1*2, 1*4, 1*8, *16, *32')

    # Add categories to the session
    db.session.add_all([category1, category2, category3, category4])

    # Commit the session to the database
    db.session.commit()

    # Create items for Category 1
    item1 = Item(name='Routers', category=category1)
    item2 = Item(name='Batchcoil', category=category1)
    item3 = Item(name='ATB', category=category1)
    item4 = Item(name='Clips', category=category1)
    item5 = Item(name='Tape', category=category1)
    item6 = Item(name='Steel Nails', category=category1)

    # Create items for Category 2
    item7 = Item(name='Overhead Cable', category=category2)
    item8 = Item(name='Jeuk', category=category2)
    item9 = Item(name='UBP', category=category2)
    item10 = Item(name='Tension Clamp', category=category2)
    item11 = Item(name='Bucklope', category=category2)
    item12 = Item(name='Scrape', category=category2)
    item13 = Item(name='Markers', category=category2)
    item14 = Item(name='Overhead Machine', category=category2)

    # Create items for Category 3
    item15 = Item(name='Climbers', category=category3)
    item16 = Item(name='Belts', category=category3)
    item17 = Item(name='Espression', category=category3)
    item18 = Item(name='Spellaton Machine', category=category3)
    item19 = Item(name='Optical Fiber Identifier', category=category3)

    # Create items for Category 4
    item20 = Item(name='Splitter Sizes 1*2', category=category4)
    item21 = Item(name='Splitter Sizes 1*4', category=category4)
    item22 = Item(name='Splitter Sizes 1*8', category=category4)
    item23 = Item(name='Splitter Sizes *16', category=category4)
    item24 = Item(name='Splitter Sizes *32', category=category4)

    # Add items to the session
    db.session.add_all([item1, item2, item3, item4, item5, item6,
                        item7, item8, item9, item10, item11, item12, item13, item14,
                        item15, item16, item17, item18, item19,
                        item20, item21, item22, item23, item24])

    # Commit the session to the database
    db.session.commit()

# Call the init_db function to initialize the database with categories and items

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

from config import config

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()


def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    migrate.init_app(app, db)

    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'  # Specify the login view for authentication

    # Register blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth_bp as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
#!/usr/bin/env python3

from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/main/routes.py
#!usr/bin/env python3
from flask import Flask, render_template, request, redirect, url_for, flash
from app import db  # Import db from the main __init__.py file
from ..models import User, Category, Item
from . import main


@main.route('/dashboard', methods=['GET'])
def dashboard():
    categories = Category.query.all()
    return render_template('dashboard.html', inventory_categories=categories)

@main.route('/', methods=['GET'])
def inventory():
    categories = Category.query.all()
    return render_template('inv.html', inventory_categories=categories)


@main.route('/update_inventory', methods=['POST'])
def update_inventory():
    if request.method == 'POST':
        category_id = request.form['category_id']
        for item in Category.query.get(category_id).items:
            quantity_taken = request.form.get(f'quantity_taken_{item.id}')
            quantity_returned = request.form.get(f'quantity_returned_{item.id}')

            if quantity_taken:
                item.quantity -= int(quantity_taken)
            if quantity_returned:
                item.quantity += int(quantity_returned)

            db.session.commit()

        flash('Inventory updated successfully!', 'success')
        return redirect(url_for('inventory'))

app/templates/categories.html
{% extends "base.html" %}

{% block head%}
{{ super() }}

{% block title %}-Dashboard{% endblock %}
{% endblock %}

{% block content %}
<header>Categories Dashboard</header>
<div class="flex">
{% for category in categories %}
    <div>
        <h2>{{ category.name }}</h2>
        <ul>
            {% for item in category.items %}
                <li>{{ item.name }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endfor %}

{% endblock %}

app/templates/dashboard.html
{% extends "base.html" %}

{% block head%}
{{ super() }}

{% block title %}-Dashboard{% endblock %}
{% endblock %}

{% block content %}
<h1>Inventory Dashboard</h1>



<div class="flex px-6 py-10 mx-auto shadow-md sm:rounded-lg">
    {% for category in categories %}
    <div class="container">
        <table class="w- text-sm text-left text-gray-500 ">
            <h2 class="text-md font-semibold text-blue-500 capitalize lg:text-xl ">{{ category.name }}</h2>
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 ">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Item
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Qty
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for item in category.items %}
                <tr class="bg-white border-b  hover:bg-gray-50 "  >
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
                        {{ item.name }}
                    </th>
                    <td class="px-6 py-4">
                        {{ item.quantity }}
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
            {% endfor %}
        </table>
    </div>
    
</div>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Inventory-Home{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
<div>
    {% if current_user.can(Permission.WRITE) %}
    {{ wtf.quick_form(form) }}
    {% endif %}
</div>
<div class="post-tabs">
    <ul class="nav nav-tabs">
        <li{% if not show_followed %} class="active"{% endif %}><a href="{{ url_for('.show_all') }}">All</a></li>
        {% if current_user.is_authenticated %}
        <li{% if show_followed %} class="active"{% endif %}><a href="{{ url_for('.show_followed') }}">Followed</a></li>
        {% endif %}
    </ul>
    {% include '_posts.html' %}
</div>
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.index') }}
</div>
{% endif %}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/inv.html
{% extends "base.html" %}

{% block head %}
{{ super() }}

<!-- Include Alpine.js from CDN -->
<script src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.2/dist/alpine.js" defer></script>
{% endblock %}

{% block title %}-Update{% endblock %}

{% block content %}
<div x-data="{ openModal: null }">
    <div class="flex flex-wrap justify-center">
        {% for category in inventory_categories %}
        <button @click="openModal = 'modal_{{ category.id }}'"
            id="modal_{{ category.id }}"
            class="px-6 py-2 m-2 tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-600 rounded-md hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-80">
            {{ category.name }}
        </button>

        <div
            x-show.transition.opacity.duration.600ms="openModal === 'modal_{{ category.id }}'"
            class="fixed inset-0 z-10 overflow-y-auto"
            aria-labelledby="modal-title"
            role="dialog" aria-modal="true">
            <div
                class="flex items-end justify-center min-h-screen px-4 pt-4 pb-20 text-center sm:block sm:p-0">
                <span class="hidden sm:inline-block sm:h-screen sm:align-middle"
                    aria-hidden="true">​</span>

                <div
                    class="relative inline-block px-4 pt-5 pb-4 overflow-hidden text-left align-bottom transition-all transform bg-white rounded-lg shadow-xl dark:bg-gray-900 sm:my-8 sm:w-full sm:max-w-sm sm:p-6 sm:align-middle">
                    <h3
                        class="text-lg font-medium leading-6 text-gray-800 capitalize dark:text-white"
                        id="modal-title">
                        {{ category.name }}
                    </h3>
                    <p class="mt-2 text-sm text-gray-500 dark:text-gray-400">
                        Enter the quantity of items you will need today.
                    </p>

                    <form class="mt-4"
                        action="{{ url_for('main.update_inventory') }}">
                        {% for item in category.items %}
                        <label for="{{ item.name }}"
                            class="text-sm text-gray-700 dark:text-gray-200">
                            {{ item.name }}
                        </label>

                        <label class="block mt-3" for="{{ item.name }}">
                            <input type="number" name="item_{{ item.id }}"
                                id="item_{{ item.id }}" placeholder="1234567890"
                                class="block w-full px-4 py-3 text-sm text-gray-700 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:focus:border-blue-300" />
                        </label>
                        {% endfor %}

                        <div class="mt-4 sm:flex sm:items-center sm:-mx-2">
                            <button type="button" @click="openModal = null"
                                class="w-full px-4 py-2 text-sm font-medium tracking-wide text-gray-700 capitalize transition-colors duration-300 transform border border-gray-200 rounded-md sm:w-1/2 sm:mx-2 dark:text-gray-200 dark:border-gray-700 dark:hover:bg-gray-800 hover:bg-gray-100 focus:outline-none focus:ring focus:ring-gray-300 focus:ring-opacity-40">
                                Cancel
                            </button>
r
                            <button type="submit"
                                class="w-full px-4 py-2 mt-3 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-600 rounded-md sm:mt-0 sm:w-1/2 sm:mx-2 hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40">
                                Update Inventory
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/inventory.html
{% extends "base.html" %}

{% block head%}
{{ super() }}

{% block title %}-Update{% endblock %}
{% endblock %}

{% block content %}

<div x-data="{ openModal: null }">
    <div class="flex flex-wrap justify-center">
        {% for category in inventory_categories %}
        <button @click="openModal = 'modal_{{ category.id }}'"
            id="modal_{{ category.id }}"
            class="px-6 py-2 m-2 tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-600 rounded-md hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-80">
            {{ category.name }}
        </button>

        <div
            x-show.transition.opacity.duration.600ms="openModal === 'modal_{{ category.id }}'"
            class="fixed inset-0 z-10 overflow-y-auto"
            aria-labelledby="modal-title"
            role="dialog" aria-modal="true">
            <div
                class="flex items-end justify-center min-h-screen px-4 pt-4 pb-20 text-center sm:block sm:p-0">
                <span class="hidden sm:inline-block sm:h-screen sm:align-middle"
                    aria-hidden="true">​</span>

                <div
                    class="relative inline-block px-4 pt-5 pb-4 overflow-hidden text-left align-bottom transition-all transform bg-white rounded-lg shadow-xl dark:bg-gray-900 sm:my-8 sm:w-full sm:max-w-sm sm:p-6 sm:align-middle">
                    <h3
                        class="text-lg font-medium leading-6 text-gray-800 capitalize dark:text-white"
                        id="modal-title">
                        {{ category.name }}
                    </h3>
                    <p class="mt-2 text-sm text-gray-500 dark:text-gray-400">
                        Enter the quantity of items you will need today.
                    </p>

                    <form class="mt-4"
                        action="{{ url_for('main.update_inventory') }}">
                        {% for item in category.items %}
                        <label for="{{ item.name }}"
                            class="text-sm text-gray-700 dark:text-gray-200">
                            {{ item.name }}
                        </label>

                        <label class="block mt-3" for="{{ item.name }}">
                            <input type="number" name="item_{{ item.id }}"
                                id="item_{{ item.id }}" placeholder="1234567890"
                                class="block w-full px-4 py-3 text-sm text-gray-700 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:focus:border-blue-300" />
                        </label>
                        {% endfor %}

                        <div class="mt-4 sm:flex sm:items-center sm:-mx-2">
                            <button type="button" @click="openModal = null"
                                class="w-full px-4 py-2 text-sm font-medium tracking-wide text-gray-700 capitalize transition-colors duration-300 transform border border-gray-200 rounded-md sm:w-1/2 sm:mx-2 dark:text-gray-200 dark:border-gray-700 dark:hover:bg-gray-800 hover:bg-gray-100 focus:outline-none focus:ring focus:ring-gray-300 focus:ring-opacity-40">
                                Cancel
                            </button>
                            
                            <button type="submit"
                                class="w-full px-4 py-2 mt-3 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-600 rounded-md sm:mt-0 sm:w-1/2 sm:mx-2 hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40">
                                Update Inventory
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<header>

</header>
<nav>

</nav>
<main>
    {% block content %}{% endblock %}
</main>
<footer>

</footer>
</body>
    {% block scripts %}{% endblock %}
</html>

app/templates/tean_create.html
{% block flashcontent %}
<!-- Display flashed messages -->
{% for message in get_flashed_messages() %}
<div class="bg-blue-200 text-blue-800 p-2 text-center">

    {{ message }}

</div>
{% endfor %}
<!--flash messages classes-->
<div class="bg-blue-200 text-blue-800 p-2 text-center">
    {% for message in get_flashed_messages() %}
    {% if 'success' in message %}
    <div class="bg-green-400 p-2 mb-2">{{ message }}</div>
    {% elif 'error' in message %}
    <div class="bg-red-400 p-2 mb-2">{{ message }}</div>
    {% else %}
    <div class="bg-gray-300 p-2 mb-2">{{ message }}</div>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}